import React, { useState } from 'react';
import { Calendar, CheckCircle, Loader2, AlertCircle } from 'lucide-react';
import { Subscription, getEffectiveTotalCost } from '../types';
import { useAppContext } from '../AppContext';
import { useTranslation } from '../i18n';
import { formatCurrency } from '../lib/utils';

interface GoogleCalendarSyncProps {
  subscriptions: Subscription[];
}

const CALENDAR_API = 'https://www.googleapis.com/calendar/v3';

async function findOrCreateBoaWalletCalendar(accessToken: string): Promise<string> {
  // List existing calendars
  const listRes = await fetch(`${CALENDAR_API}/users/me/calendarList`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!listRes.ok) {
    throw new Error(`Calendar API error: ${listRes.status}`);
  }

  const listData = await listRes.json();
  const existing = listData.items?.find(
    (cal: any) => cal.summary === 'BoaWallet'
  );

  if (existing) {
    return existing.id;
  }

  // Create a new "BoaWallet" calendar
  const createRes = await fetch(`${CALENDAR_API}/calendars`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      summary: 'BoaWallet',
      description: 'Lembretes de pagamentos e assinaturas do BoaWallet',
      timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    }),
  });

  if (!createRes.ok) {
    throw new Error(`Failed to create calendar: ${createRes.status}`);
  }

  const newCal = await createRes.json();
  return newCal.id;
}

async function clearBoaWalletEvents(accessToken: string, calendarId: string): Promise<void> {
  // List all existing events in the calendar
  let pageToken: string | undefined;
  const eventIds: string[] = [];

  do {
    const url = new URL(`${CALENDAR_API}/calendars/${encodeURIComponent(calendarId)}/events`);
    url.searchParams.set('maxResults', '250');
    if (pageToken) url.searchParams.set('pageToken', pageToken);

    const res = await fetch(url.toString(), {
      headers: { Authorization: `Bearer ${accessToken}` },
    });

    if (!res.ok) break;

    const data = await res.json();
    data.items?.forEach((event: any) => eventIds.push(event.id));
    pageToken = data.nextPageToken;
  } while (pageToken);

  // Delete all old events (in batches)
  for (const eventId of eventIds) {
    await fetch(
      `${CALENDAR_API}/calendars/${encodeURIComponent(calendarId)}/events/${eventId}`,
      {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${accessToken}` },
      }
    );
  }
}

async function createSubscriptionEvent(
  accessToken: string,
  calendarId: string,
  sub: Subscription,
  language: string
): Promise<void> {
  const now = new Date();
  const dueDate = new Date(now.getFullYear(), now.getMonth(), sub.dueDate);
  // If the due date this month has passed, start from next month
  if (dueDate < now) {
    dueDate.setMonth(dueDate.getMonth() + 1);
  }

  const effectiveCost = getEffectiveTotalCost(sub);
  const costStr = formatCurrency(effectiveCost.amount, effectiveCost.currency);

  const startDate = dueDate.toISOString().split('T')[0]; // YYYY-MM-DD

  const recurrence =
    sub.billingCycle === 'Monthly'
      ? 'RRULE:FREQ=MONTHLY'
      : 'RRULE:FREQ=YEARLY';

  const description = [
    `💰 ${language === 'pt' ? 'Custo' : 'Cost'}: ${costStr}`,
    sub.billingCycle === 'Monthly'
      ? `📅 ${language === 'pt' ? 'Mensal' : 'Monthly'}`
      : `📅 ${language === 'pt' ? 'Anual' : 'Yearly'}`,
    sub.paymentMethod ? `💳 ${sub.paymentMethod}` : '',
    sub.paymentSource ? `🏦 ${sub.paymentSource}` : '',
    sub.notes ? `\n📝 ${sub.notes}` : '',
    `\n— ${language === 'pt' ? 'Gerado pelo BoaWallet' : 'Generated by BoaWallet'}`,
  ]
    .filter(Boolean)
    .join('\n');

  const eventBody = {
    summary: `${sub.emoji || '📌'} ${sub.name} — ${costStr}`,
    description,
    start: {
      date: startDate,
    },
    end: {
      date: startDate,
    },
    recurrence: [recurrence],
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 1440 }, // 1 day before
        { method: 'popup', minutes: 60 },   // 1 hour before
      ],
    },
    colorId: '9', // Blueberry
  };

  const res = await fetch(
    `${CALENDAR_API}/calendars/${encodeURIComponent(calendarId)}/events`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(eventBody),
    }
  );

  if (!res.ok) {
    const errText = await res.text();
    console.error(`Failed to create event for ${sub.name}:`, errText);
  }
}

export function GoogleCalendarSync({ subscriptions }: GoogleCalendarSyncProps) {
  const { language, googleAccessToken, user } = useAppContext();
  const t = useTranslation(language);
  const [syncing, setSyncing] = useState(false);
  const [syncResult, setSyncResult] = useState<'success' | 'error' | null>(null);
  const [syncMessage, setSyncMessage] = useState('');

  const activeSubs = subscriptions.filter((s) => !s.status?.startsWith('cancelled'));

  const handleSync = async () => {
    if (!googleAccessToken) {
      setSyncResult('error');
      setSyncMessage(
        language === 'pt'
          ? 'Faça login com Google primeiro para sincronizar.'
          : 'Please sign in with Google first to sync.'
      );
      setTimeout(() => setSyncResult(null), 4000);
      return;
    }

    if (activeSubs.length === 0) {
      setSyncResult('error');
      setSyncMessage(
        language === 'pt'
          ? 'Nenhuma assinatura ativa para sincronizar.'
          : 'No active subscriptions to sync.'
      );
      setTimeout(() => setSyncResult(null), 4000);
      return;
    }

    setSyncing(true);
    setSyncResult(null);

    try {
      // 1. Find or create the BoaWallet calendar
      const calendarId = await findOrCreateBoaWalletCalendar(googleAccessToken);

      // 2. Clear existing BoaWallet events to avoid duplicates
      await clearBoaWalletEvents(googleAccessToken, calendarId);

      // 3. Create an event for each active subscription
      for (const sub of activeSubs) {
        await createSubscriptionEvent(googleAccessToken, calendarId, sub, language);
      }

      setSyncResult('success');
      setSyncMessage(
        language === 'pt'
          ? `${activeSubs.length} lembrete(s) sincronizado(s) com o Google Calendar!`
          : `${activeSubs.length} reminder(s) synced to Google Calendar!`
      );
    } catch (error: any) {
      console.error('Calendar sync error:', error);
      setSyncResult('error');
      // If token expired, suggest re-login
      if (error.message?.includes('401') || error.message?.includes('403')) {
        setSyncMessage(
          language === 'pt'
            ? 'Token expirado. Faça logout e login novamente.'
            : 'Token expired. Please sign out and sign in again.'
        );
      } else {
        setSyncMessage(
          language === 'pt'
            ? 'Erro ao sincronizar. Tente novamente.'
            : 'Sync failed. Please try again.'
        );
      }
    } finally {
      setSyncing(false);
      setTimeout(() => setSyncResult(null), 5000);
    }
  };

  // Also keep the ICS fallback for non-logged-in users
  const generateGenericICS = () => {
    let icsContent = `BEGIN:VCALENDAR\nVERSION:2.0\nCALSCALE:GREGORIAN\n`;
    const now = new Date();

    activeSubs.forEach((sub) => {
      const dueDate = new Date(now.getFullYear(), now.getMonth(), sub.dueDate);
      if (dueDate < now) {
        dueDate.setMonth(dueDate.getMonth() + 1);
      }

      const start = dueDate.toISOString().replace(/-|:|\.\d+/g, '');
      const end = new Date(dueDate.getTime() + 60 * 60 * 1000)
        .toISOString()
        .replace(/-|:|\.\d+/g, '');

      icsContent += `BEGIN:VEVENT\n`;
      icsContent += `DTSTART:${start}\n`;
      icsContent += `DTEND:${end}\n`;
      icsContent += `SUMMARY:BoaWallet: ${sub.name}\n`;
      icsContent += `DESCRIPTION:Cost: ${formatCurrency(
        getEffectiveTotalCost(sub).amount,
        getEffectiveTotalCost(sub).currency
      )}.\n`;
      icsContent += `RRULE:FREQ=${
        sub.billingCycle === 'Monthly' ? 'MONTHLY' : 'YEARLY'
      }\n`;
      icsContent += `END:VEVENT\n`;
    });

    icsContent += `END:VCALENDAR`;

    const blob = new Blob([icsContent], {
      type: 'text/calendar;charset=utf-8',
    });
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.setAttribute('download', `boawallet_calendario.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="flex flex-col items-end gap-2 relative">
      {/* Main button: Google Calendar sync if logged in, ICS export if not */}
      {user && googleAccessToken ? (
        <button
          onClick={handleSync}
          disabled={syncing || activeSubs.length === 0}
          className="flex items-center gap-2 bg-[#1a1a1a] border border-gray-800 hover:bg-[#2a2a2a] text-gray-200 px-4 py-2 rounded-xl text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {syncing ? (
            <Loader2 size={16} className="text-emerald-400 animate-spin" />
          ) : (
            <Calendar size={16} className="text-emerald-400" />
          )}
          <span className="hidden sm:inline">
            {syncing
              ? language === 'pt'
                ? 'Sincronizando...'
                : 'Syncing...'
              : language === 'pt'
              ? 'Sincronizar Calendário'
              : 'Sync Calendar'}
          </span>
        </button>
      ) : (
        <button
          onClick={generateGenericICS}
          disabled={activeSubs.length === 0}
          className="flex items-center gap-2 bg-[#1a1a1a] border border-gray-800 hover:bg-[#2a2a2a] text-gray-200 px-4 py-2 rounded-xl text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Calendar size={16} className="text-emerald-400" />
          <span className="hidden sm:inline">
            {language === 'pt' ? 'Exportar ICS' : 'Export ICS'}
          </span>
        </button>
      )}

      {/* Sync result toast */}
      {syncResult && (
        <div
          className={`absolute top-full right-0 mt-2 px-4 py-3 rounded-xl shadow-lg text-sm font-medium z-50 whitespace-nowrap flex items-center gap-2 ${
            syncResult === 'success'
              ? 'bg-emerald-900/90 text-emerald-200 border border-emerald-700'
              : 'bg-red-900/90 text-red-200 border border-red-700'
          }`}
        >
          {syncResult === 'success' ? (
            <CheckCircle size={16} />
          ) : (
            <AlertCircle size={16} />
          )}
          {syncMessage}
        </div>
      )}
    </div>
  );
}
