import { Subscription } from './types';

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: '1',
    name: 'Netflix',
    emoji: '🍿',
    logoUrl: 'https://logo.clearbit.com/netflix.com',
    category: 'Streaming',
    costAmount: 19.99,
    costCurrency: 'USD',
    billingCycle: 'Monthly',
    dueDate: 15,
    subItems: [],
    paymentMethod: 'Cartão de Crédito',
    paymentSource: 'Revolut',
    bankLogoUrl: 'https://logo.clearbit.com/revolut.com',
    hasCashback: false,
    cashbackPercentage: 0,
    hasIncome: true,
    incomeAmount: 10,
    incomeCurrency: 'EUR',
    incomeFrequency: 'Monthly',
    incomeSourceDescription: 'Dividido com 2 amigos',
  },
  {
    id: '2',
    name: 'YouTube Premium',
    emoji: '▶️',
    logoUrl: 'https://logo.clearbit.com/youtube.com',
    category: 'Streaming',
    costAmount: 24.90,
    costCurrency: 'BRL',
    billingCycle: 'Monthly',
    dueDate: 5,
    subItems: [
      { id: '2-1', name: 'Clube de Canais (Tech)', costAmount: 7.99 },
      { id: '2-2', name: 'Clube de Canais (Games)', costAmount: 4.99 }
    ],
    paymentMethod: 'Cartão de Crédito',
    paymentSource: 'Nubank',
    bankLogoUrl: 'https://logo.clearbit.com/nubank.com.br',
    hasCashback: true,
    cashbackPercentage: 1.5,
    hasIncome: false,
    incomeAmount: 0,
    incomeCurrency: 'BRL',
    incomeFrequency: 'Monthly',
    incomeSourceDescription: '',
  },
  {
    id: '3',
    name: 'Adobe Creative Cloud',
    emoji: '🎨',
    logoUrl: 'https://logo.clearbit.com/adobe.com',
    category: 'Software',
    costAmount: 54.99,
    costCurrency: 'USD',
    billingCycle: 'Monthly',
    dueDate: 22,
    subItems: [],
    paymentMethod: 'Cartão de Crédito',
    paymentSource: 'Wise',
    bankLogoUrl: 'https://logo.clearbit.com/wise.com',
    hasCashback: false,
    cashbackPercentage: 0,
    hasIncome: false,
    incomeAmount: 0,
    incomeCurrency: 'USD',
    incomeFrequency: 'Monthly',
    incomeSourceDescription: '',
  },
  {
    id: '4',
    name: 'Xbox Game Pass',
    emoji: '🎮',
    logoUrl: 'https://logo.clearbit.com/xbox.com',
    category: 'Games',
    costAmount: 159.00,
    costCurrency: 'TRY',
    billingCycle: 'Monthly',
    dueDate: 10,
    subItems: [],
    paymentMethod: 'Gift Card',
    paymentSource: 'Outro',
    hasCashback: false,
    cashbackPercentage: 0,
    hasIncome: false,
    incomeAmount: 0,
    incomeCurrency: 'TRY',
    incomeFrequency: 'Monthly',
    incomeSourceDescription: '',
  }
];
